---
title: "intro"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 7,
  fig.height = 5,
  comment = "#>"
)
```

```{r setup}
library(BayesProj)
library(BayesRates)
library(dplyr)
library(ggplot2)
```



```{r}
res <- smooth_agetime(nevent_df = nz_divorces,
                      py_df = nz_population,
                      age_width_df = nz_age_width_df,
                      age_min = 15,
                      byvar = "sex",
                      spec_time = TimeFixed())
res
```

```{r}
rates <- total_rate(res)
rates
```

```{r}
data <- rates |>
  select(sex, time, total = .probability)
```

## Model for indicator

```{r}
fitted <- fit_ts(data, 
                 indvar = "total",
                 byvar = "sex")
```


Model using AR1

```{r}
fitted_ar <- fit_ts(data,
                    spec_ts = AR1(),
                    indvar = "total",
                    byvar = "sex")
```


## Project indicator without benchmarks

```{r}
projected <- project_ts(fitted, 
                        time_labels = 2022:2030)
```

```{r}
vals <- composite(projected) |>
  mutate(time = as.integer(time)) ## not sure why it's character  
```

```{r}
ggplot(vals, aes(x = time, y = total)) +
  facet_wrap(vars(sex)) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper), 
              fill = "salmon") +
  geom_line(col = "darkblue", 
            linewidth = 0.5)
```

With AR1 model


```{r}
projected_ar <- project_ts(fitted_ar, 
                        time_labels = 2022:2030)
```

```{r}
vals_ar <- composite(projected_ar) |>
  mutate(time = as.integer(time)) ## not sure why it's character  
```

```{r}
ggplot(vals_ar, aes(x = time, y = total)) +
  facet_wrap(vars(sex)) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper), 
              fill = "salmon") +
  geom_line(col = "darkblue", 
            linewidth = 0.5)
```



## Project indicator with benchmarks

```{r}
bench <- Benchmarks(data.frame(time = 2030,
                               q50 = 0.15,
                               q90 = 0.2))
```


```{r}
projected_bench <- project_ts(fitted, 
                              spec_bench = bench,
                              time_labels = 2022:2030)
```

```{r}
vals_bench <- composite(projected_bench) |>
  mutate(time = as.integer(time)) ## not sure why it's character  
```

```{r}
ggplot(vals_bench, aes(x = time, y = total)) +
  facet_wrap(vars(sex)) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper), 
              fill = "salmon") +
  geom_line(col = "darkblue", 
            linewidth = 0.5) +
  geom_ribbon(aes(ymin = .bench.lower,
                  ymax = .bench.upper),
              fill = "lightblue",
              alpha = 0.5) +
  geom_line(aes(y = .bench.mid),
            col = "blue",
            linewidth = 0.5,
            alpha = 0.5)
```

With AR model


```{r}
projected_bench_ar <- project_ts(fitted_ar, 
                              spec_bench = bench,
                              time_labels = 2022:2030)
```

```{r}
vals_bench_ar <- composite(projected_bench_ar) |>
  mutate(time = as.integer(time)) ## not sure why it's character  
```

```{r}
ggplot(vals_bench_ar, aes(x = time, y = total)) +
  facet_wrap(vars(sex)) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper), 
              fill = "salmon") +
  geom_line(col = "darkblue", 
            linewidth = 0.5) +
  geom_ribbon(aes(ymin = .bench.lower,
                  ymax = .bench.upper),
              fill = "lightblue",
              alpha = 0.5) +
  geom_line(aes(y = .bench.mid),
            col = "blue",
            linewidth = 0.5,
            alpha = 0.5)
```



## Model for indicator, on log scale

```{r}
fitted_log <- fit_ts(data, 
                     indvar = "total",
                     byvar = "sex", 
                     log = TRUE)
```



```{r}
projected_log <- project_ts(fitted, 
                            spec_bench = bench,
                            time_labels = 2022:2030)
```

```{r}
vals_log <- composite(projected_log) |>
  mutate(time = as.integer(time)) ## not sure why it's character  
```

```{r}
ggplot(vals_log, aes(x = time, y = total)) +
  facet_wrap(vars(sex)) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper), 
              fill = "salmon") +
  geom_line(col = "darkblue", 
            linewidth = 0.5) +
  geom_ribbon(aes(ymin = .bench.lower,
                  ymax = .bench.upper),
              fill = "lightblue",
              alpha = 0.5) +
  geom_line(aes(y = .bench.mid),
            col = "blue",
            linewidth = 0.5,
            alpha = 0.5)
```
